drop table if exists restaurants cascade;

drop table if exists menu_items cascade;

drop table if exists profiles cascade;

drop type if exists order_status CASCADE;

drop table if exists orders cascade;

drop table if exists order_items cascade;

drop table if exists cart cascade;

create table if not exists restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  cuisine text not null,
  price_range text,
  delivery_time text,
  image_url text,
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null
);

create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants (id) not null,
  name text not null,
  description text,
  price decimal(10, 2) not null,
  category text,
  image_url text,
  vegetarian boolean,
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null
);

create table if not exists profiles (
  id uuid references auth.users (id) on delete cascade primary key,
  full_name text not null,
  address text not null,
  phone text not null,
  preferences jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default timezone ('utc'::text, now()) not null
);

create type order_status as ENUM(
  'pending',
  'preparing',
  'on_the_way',
  'delivered',
  'cancelled'
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) not null,
  restaurant_id bigint references restaurants (id) not null,
  status order_status not null default 'pending',
  total_amount decimal(10, 2) not null,
  delivery_address text not null,
  payment_method text not null,
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders (id) on delete cascade not null,
  menu_item_id bigint references menu_items (id) not null,
  quantity integer not null default 1,
  price_at_time decimal(10, 2) not null
);

create table if not exists cart (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) not null,
  menu_item_id bigint references menu_items (id) not null,
  quantity integer not null default 1 check (
    quantity >= 1
    and quantity <= 5
  ),
  created_at timestamp with time zone default timezone ('utc'::text, now()) not null,
  unique (user_id, menu_item_id)
);

create table if not exists ratings (
  id BIGINT generated by default as identity primary key,
  user_id UUID references auth.users not null,
  restaurant_id BIGINT references restaurants not null,
  order_id BIGINT references orders,
  rating INTEGER not null check (
    rating >= 1
    and rating <= 5
  ),
  created_at timestamp with time zone default TIMEZONE ('utc'::TEXT, NOW()) not null,
  unique (user_id, order_id)
);

create table if not exists favorites (
  id BIGINT generated by default as identity primary key,
  user_id UUID references auth.users not null,
  restaurant_id BIGINT references restaurants not null,
  created_at timestamp with time zone default TIMEZONE ('utc'::TEXT, NOW()) not null,
  unique (user_id, restaurant_id)
);
